"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class platoon_member_state_t(object):
    __slots__ = ["vehicle_index", "speed", "acceleration", "relative_displacement"]

    def __init__(self):
        self.vehicle_index = 0
        self.speed = 0.0
        self.acceleration = 0.0
        self.relative_displacement = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(platoon_member_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hddd", self.vehicle_index, self.speed, self.acceleration, self.relative_displacement))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != platoon_member_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return platoon_member_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = platoon_member_state_t()
        self.vehicle_index, self.speed, self.acceleration, self.relative_displacement = struct.unpack(">hddd", buf.read(26))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if platoon_member_state_t in parents: return 0
        tmphash = (0xa0cd8b09933035f6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if platoon_member_state_t._packed_fingerprint is None:
            platoon_member_state_t._packed_fingerprint = struct.pack(">Q", platoon_member_state_t._get_hash_recursive([]))
        return platoon_member_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

