"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class platoon_controller_info_t(object):
    __slots__ = ["utime", "control_mode", "collision_time", "front_speed", "front_distance", "turn_light", "beam"]

    def __init__(self):
        self.utime = 0
        self.control_mode = 0
        self.collision_time = 0.0
        self.front_speed = 0.0
        self.front_distance = 0.0
        self.turn_light = 0
        self.beam = 0

    def encode(self):
        buf = BytesIO()
        buf.write(platoon_controller_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhdddbb", self.utime, self.control_mode, self.collision_time, self.front_speed, self.front_distance, self.turn_light, self.beam))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != platoon_controller_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return platoon_controller_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = platoon_controller_info_t()
        self.utime, self.control_mode, self.collision_time, self.front_speed, self.front_distance, self.turn_light, self.beam = struct.unpack(">qhdddbb", buf.read(36))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if platoon_controller_info_t in parents: return 0
        tmphash = (0x262be74bf8302ee5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if platoon_controller_info_t._packed_fingerprint is None:
            platoon_controller_info_t._packed_fingerprint = struct.pack(">Q", platoon_controller_info_t._get_hash_recursive([]))
        return platoon_controller_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

