"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import lcmtypes.moving_object_t

class lidar_object_t(object):
    __slots__ = ["utime", "leftFrontObject", "frontObject", "rightFrontObject", "leftRearObject", "rearObject", "rightRearObject", "leftObject", "rightObject"]

    def __init__(self):
        self.utime = 0
        self.leftFrontObject = lcmtypes.moving_object_t()
        self.frontObject = lcmtypes.moving_object_t()
        self.rightFrontObject = lcmtypes.moving_object_t()
        self.leftRearObject = lcmtypes.moving_object_t()
        self.rearObject = lcmtypes.moving_object_t()
        self.rightRearObject = lcmtypes.moving_object_t()
        self.leftObject = lcmtypes.moving_object_t()
        self.rightObject = lcmtypes.moving_object_t()

    def encode(self):
        buf = BytesIO()
        buf.write(lidar_object_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.leftFrontObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.leftFrontObject._encode_one(buf)
        assert self.frontObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.frontObject._encode_one(buf)
        assert self.rightFrontObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.rightFrontObject._encode_one(buf)
        assert self.leftRearObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.leftRearObject._encode_one(buf)
        assert self.rearObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.rearObject._encode_one(buf)
        assert self.rightRearObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.rightRearObject._encode_one(buf)
        assert self.leftObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.leftObject._encode_one(buf)
        assert self.rightObject._get_packed_fingerprint() == lcmtypes.moving_object_t._get_packed_fingerprint()
        self.rightObject._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lidar_object_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lidar_object_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lidar_object_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.leftFrontObject = lcmtypes.moving_object_t._decode_one(buf)
        self.frontObject = lcmtypes.moving_object_t._decode_one(buf)
        self.rightFrontObject = lcmtypes.moving_object_t._decode_one(buf)
        self.leftRearObject = lcmtypes.moving_object_t._decode_one(buf)
        self.rearObject = lcmtypes.moving_object_t._decode_one(buf)
        self.rightRearObject = lcmtypes.moving_object_t._decode_one(buf)
        self.leftObject = lcmtypes.moving_object_t._decode_one(buf)
        self.rightObject = lcmtypes.moving_object_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lidar_object_t in parents: return 0
        newparents = parents + [lidar_object_t]
        tmphash = (0x560c1f6f864502c7+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)+ lcmtypes.moving_object_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lidar_object_t._packed_fingerprint is None:
            lidar_object_t._packed_fingerprint = struct.pack(">Q", lidar_object_t._get_hash_recursive([]))
        return lidar_object_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

