"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mo_paras_info_t(object):
    __slots__ = ["fBF", "fBase", "nVanishingPointX", "nVanishingPointY"]

    def __init__(self):
        self.fBF = 0.0
        self.fBase = 0.0
        self.nVanishingPointX = 0
        self.nVanishingPointY = 0

    def encode(self):
        buf = BytesIO()
        buf.write(mo_paras_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddii", self.fBF, self.fBase, self.nVanishingPointX, self.nVanishingPointY))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mo_paras_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mo_paras_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mo_paras_info_t()
        self.fBF, self.fBase, self.nVanishingPointX, self.nVanishingPointY = struct.unpack(">ddii", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mo_paras_info_t in parents: return 0
        tmphash = (0xc0ab93bba6fb662f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mo_paras_info_t._packed_fingerprint is None:
            mo_paras_info_t._packed_fingerprint = struct.pack(">Q", mo_paras_info_t._get_hash_recursive([]))
        return mo_paras_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

