"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class camera_line_info_t(object):
    __slots__ = ["confidence", "type", "lineColor", "length", "a", "b", "c", "d"]

    def __init__(self):
        self.confidence = 0.0
        self.type = 0
        self.lineColor = 0
        self.length = 0.0
        self.a = 0.0
        self.b = 0.0
        self.c = 0.0
        self.d = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(camera_line_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fbbfffff", self.confidence, self.type, self.lineColor, self.length, self.a, self.b, self.c, self.d))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_line_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_line_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = camera_line_info_t()
        self.confidence, self.type, self.lineColor, self.length, self.a, self.b, self.c, self.d = struct.unpack(">fbbfffff", buf.read(26))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if camera_line_info_t in parents: return 0
        tmphash = (0xcd8d81c467cdab4a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if camera_line_info_t._packed_fingerprint is None:
            camera_line_info_t._packed_fingerprint = struct.pack(">Q", camera_line_info_t._get_hash_recursive([]))
        return camera_line_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

