"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class key_point_t(object):
    __slots__ = ["x", "y"]

    def __init__(self):
        self.x = 0.0
        self.y = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(key_point_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ff", self.x, self.y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != key_point_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return key_point_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = key_point_t()
        self.x, self.y = struct.unpack(">ff", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if key_point_t in parents: return 0
        tmphash = (0x7c2d87baacd686e3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if key_point_t._packed_fingerprint is None:
            key_point_t._packed_fingerprint = struct.pack(">Q", key_point_t._get_hash_recursive([]))
        return key_point_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

