"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class map_point_t(object):
    __slots__ = ["lon", "lat", "localX", "localY", "globalX", "globalY"]

    def __init__(self):
        self.lon = 0.0
        self.lat = 0.0
        self.localX = 0.0
        self.localY = 0.0
        self.globalX = 0.0
        self.globalY = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(map_point_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddffff", self.lon, self.lat, self.localX, self.localY, self.globalX, self.globalY))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != map_point_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return map_point_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = map_point_t()
        self.lon, self.lat, self.localX, self.localY, self.globalX, self.globalY = struct.unpack(">ddffff", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if map_point_t in parents: return 0
        tmphash = (0xfc4b06379f1b6db6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if map_point_t._packed_fingerprint is None:
            map_point_t._packed_fingerprint = struct.pack(">Q", map_point_t._get_hash_recursive([]))
        return map_point_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

