"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import lcmtypes.map_point_t

class map_road_boundary_t(object):
    __slots__ = ["pointCount", "points", "height", "property"]

    def __init__(self):
        self.pointCount = 0
        self.points = []
        self.height = 0.0
        self.property = 0

    def encode(self):
        buf = BytesIO()
        buf.write(map_road_boundary_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.pointCount))
        for i0 in range(self.pointCount):
            assert self.points[i0]._get_packed_fingerprint() == lcmtypes.map_point_t._get_packed_fingerprint()
            self.points[i0]._encode_one(buf)
        buf.write(struct.pack(">fb", self.height, self.property))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != map_road_boundary_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return map_road_boundary_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = map_road_boundary_t()
        self.pointCount = struct.unpack(">h", buf.read(2))[0]
        self.points = []
        for i0 in range(self.pointCount):
            self.points.append(lcmtypes.map_point_t._decode_one(buf))
        self.height, self.property = struct.unpack(">fb", buf.read(5))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if map_road_boundary_t in parents: return 0
        newparents = parents + [map_road_boundary_t]
        tmphash = (0x11578e06723aab67+ lcmtypes.map_point_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if map_road_boundary_t._packed_fingerprint is None:
            map_road_boundary_t._packed_fingerprint = struct.pack(">Q", map_road_boundary_t._get_hash_recursive([]))
        return map_road_boundary_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

