"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mo_line_info_t(object):
    __slots__ = ["Id", "bValid", "realPointXZ"]

    def __init__(self):
        self.Id = 0
        self.bValid = 0
        self.realPointXZ = [ [ 0 for dim1 in range(2) ] for dim0 in range(10) ]

    def encode(self):
        buf = BytesIO()
        buf.write(mo_line_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ib", self.Id, self.bValid))
        for i0 in range(10):
            buf.write(struct.pack('>2h', *self.realPointXZ[i0][:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mo_line_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mo_line_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mo_line_info_t()
        self.Id, self.bValid = struct.unpack(">ib", buf.read(5))
        self.realPointXZ = []
        for i0 in range(10):
            self.realPointXZ.append(struct.unpack('>2h', buf.read(4)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mo_line_info_t in parents: return 0
        tmphash = (0x1b61285a7f5d0e2c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mo_line_info_t._packed_fingerprint is None:
            mo_line_info_t._packed_fingerprint = struct.pack(">Q", mo_line_info_t._get_hash_recursive([]))
        return mo_line_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

