"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class steer_cmd_t(object):
    __slots__ = ["utime", "steer_pos", "steer_spe"]

    def __init__(self):
        self.utime = 0
        self.steer_pos = 0.0
        self.steer_spe = 0

    def encode(self):
        buf = BytesIO()
        buf.write(steer_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfi", self.utime, self.steer_pos, self.steer_spe))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != steer_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return steer_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = steer_cmd_t()
        self.utime, self.steer_pos, self.steer_spe = struct.unpack(">qfi", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if steer_cmd_t in parents: return 0
        tmphash = (0x713b794ac05ee383) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if steer_cmd_t._packed_fingerprint is None:
            steer_cmd_t._packed_fingerprint = struct.pack(">Q", steer_cmd_t._get_hash_recursive([]))
        return steer_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

